clone_depth: 1
init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
    # Tell msys2 to add mingw64 to the path
    MSYSTEM: MINGW64
    # Tell msys2 to inherit the current directory when starting the shell
    CHERE_INVOKING: 1

    
build_script:
    # Create ZIP package
     # set LIBIIO_VERSION to current project version determined by cmake
    - git clone https://github.com/gnieboer/GNURadio_Windows_Build_Scripts.git
    - cd C:\projects\gnuradio-windows-builds\GNURadio_Windows_Build_Scripts
    - ps: choco install doxygen.install --version 1.8.14
    - ps: ./~RUNME_FIRST.ps1
          
on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))